In [2]:
from scipy import linalg
import numpy as np

In [3]:
x = np.asmatrix('[1,2,3;3,4,5;6,7,8]')
x

matrix([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [5]:
eigen_value, eigen_vector = linalg.eig(x)
eigen_value, eigen_vector

(array([ 1.40663730e+01+0.j, -1.06637298e+00+0.j,  3.43927949e-17+0.j]),
 array([[ 0.26564776,  0.74442863,  0.40824829],
        [ 0.49120712,  0.19070122, -0.81649658],
        [ 0.82954616, -0.63988988,  0.40824829]]))

In [6]:
#Singular value decompostion

P = eigen_vector
P_inverse = linalg.inv(eigen_vector)

D = []

for index,eg_value in enumerate(eigen_value):
    row = np.zeros(3)
    row[index] = eg_value
    D.append(row)
D = np.array(D)

print(P @ D @ P_inverse)

[[1. 2. 3.]
 [3. 4. 5.]
 [6. 7. 8.]]


C:\Users\ACER\AppData\Local\Temp\ipykernel_48260\2907785935.py:10: ComplexWarning: Casting complex values to real discards the imaginary part
  row[index] = eg_value
