In [1]:
from scipy import special
import numpy as np

In [2]:
x = special.cbrt([8,27,81])
x

array([2.        , 3.        , 4.32674871])

In [4]:
y = special.exp10([1,2,3])
y

array([  10.,  100., 1000.])

In [6]:
z = special.exp2([1,2,3])
z

array([2., 4., 8.])

In [8]:
special.comb(10,3) , special.perm(10,3)

(120.0, 720.0)

In [12]:
k = special.logsumexp([1,2,3,4])
k

4.440189698561196

In [15]:
j = special.lambertw(1j) 
j

(0.37469902073711747+0.5764127230314352j)