In [1]:
import numpy as np
import scipy
from scipy import stats

In [3]:
data = [1,2,3,4,5,6,7,8,9,-1,2,-3,-4,-5]
des = stats.describe(data)
des

DescribeResult(nobs=14, minmax=(-5, 9), mean=2.4285714285714284, variance=19.802197802197803, skewness=-0.23560721225568543, kurtosis=-1.0476138856690251)

In [6]:
data = [1,2,3,4,5,6,7,8,9,-1,2,-3,-4,-5]
des = stats.describe(data)
for key,value in des._asdict().items():
    print(f'Key {key} : Value {value}')

Key nobs : Value 14
Key minmax : Value (-5, 9)
Key mean : Value 2.4285714285714284
Key variance : Value 19.802197802197803
Key skewness : Value -0.23560721225568543
Key kurtosis : Value -1.0476138856690251


In [11]:
array = np.asmatrix('[1,2,3;4,5,6;1,2,1; 7,1,1]')
desarray = stats.describe(array)
print(array)
for key,value in desarray._asdict().items():
    print(f'Key {key} : Value {value}')
    

[[1 2 3]
 [4 5 6]
 [1 2 1]
 [7 1 1]]
Key nobs : Value 4
Key minmax : Value (array([1, 1, 1]), array([7, 5, 6]))
Key mean : Value [3.25 2.5  2.75]
Key variance : Value [8.25       3.         5.58333333]
Key skewness : Value [0.4933822  0.88888889 0.68925448]
Key kurtosis : Value [-1.37190083 -0.81481481 -1.14190243]


In [17]:
array = np.array([-2,-1,0,1,2])

distribution = stats.norm(0,2)  #mean , std


print('Area left to point on that area, cumulative distrubution is  : ', distribution.cdf(array))
print(f'PPF value, which value satisying the given area points, is {distribution.ppf(0.15)}')
print(f'Sample distribution is {distribution.rvs(size=5)}')

Area left to point on that area, cumulative distrubution is  :  [0.15865525 0.30853754 0.5        0.69146246 0.84134475]
PPF value, which value satisying the given area points, is -2.0728667789875797
Sample distribution is [-0.40677095 -0.4922798  -2.16514768 -0.1494718  -1.56475099]
